import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen flex flex-col bg-white text-black dark:bg-gray-900 dark:text-white">
        {/* ヘッダー */}
        <Header/>
        {/* メインコンテンツ */}
        <main className="container mx-auto p-4">
          {children}
        </main>
        <footer className="bg-gray-800 text-white p-4 dark:bg-gray-700 text-center">
          <p>&copy; 2024 CK Blog. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
